name: deploy-pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Build Vue project
        run: npm run build
      - name: Build VuePress project
        run: npm run docs:build
      - name: Prepare deployment directory
        run: |
          mkdir -p deployment/docs
          cp -r ./dist/* deployment/
          cp -r ./docs/.vuepress/dist/* deployment/docs/
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./deployment"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4